version: 0.0
os: linux
files:
  - source: /app.js
    destination: /home/ec2-user/
hooks:
  BeforeInstall:
    - location: scripts/stop-app.sh
    timeout: 150
    runas: root
  AfterInstall:
    - location: scripts/start-app.sh
    timeout: 150
    runas: root
